### ISSUE TITLE
Github releases page does not contain newer versions

### ISSUE THREAD

**Issue by aldas** [stretchr/testify#1295]
Please consider changing testify release process so new releases will be visible from Github release page. Seeing latest version date at the right side of the repository landing page in Github is useful.

https://github.com/stretchr/testify/releases
https://github.com/stretchr/testify/tags

Currently these pages are quite different. If you are used to check releases page the current version then what you would see is quite different what tags page shows. 

It does not need to contain fancy changelog or changelog at all.

**Comment by illume** [comment]
This link was useful for me to see the changes, and maybe it is for someone else:
https://github.com/stretchr/testify/compare/v1.7.0...v1.8.1

**Comment by aldas** [comment]
I think this would help

Create github workflow action (https://github.com/softprops/action-gh-release) that creates new release when new tag is pushed.  This way current testify maintainer/author do not need to change their habbits - this action will kick in on matching tag push.

Workflow file:
```yaml
name: release on new tag

# this flow will be run only when new tags are pushed that match our pattern
on:
  push:
    tags:
      - "v[0-9]+\.[0-9]+\.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create release
        uses: softprops/action-gh-release@v1
```
